name: cm23mp
description: Multiplatform App CodeMash 2023

publish_to: 'none' 

version: 1.0.0+4

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flex_seed_scheme: ^1.1.0
  flutter:
    sdk: flutter
  # freezed_annotation: ^2.2.0
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  # json_annotation: ^4.7.0

dev_dependencies:
  # build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  # freezed: ^2.3.2
  # json_serializable: ^6.5.4
  lint: ^2.0.1

flutter:
  uses-material-design: true
