name: cm23mp
description: Multiplatform App CodeMash 2023

publish_to: 'none' 

version: 1.0.0+3

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flex_seed_scheme: ^1.1.0
  flutter:
    sdk: flutter
  # go_router: ^6.0.0
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # lint: ^2.0.1

flutter:
  uses-material-design: true
