name: cm23mp
description: Multiplatform App CodeMash 2023

publish_to: 'none' 

version: 1.0.0+5

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  # auto_size_text: ^3.0.0
  # cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flex_seed_scheme: ^1.1.0
  flutter:
    sdk: flutter
  # flutter_widget_from_html: ^0.9.0+2
  freezed_annotation: ^2.2.0
  go_router: ^6.0.0
  google_fonts: ^3.0.1
  # hooks_riverpod: ^2.1.3
  json_annotation: ^4.7.0
  # riverpod_annotation: ^1.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  lint: ^2.0.1
  # riverpod_generator: ^1.1.1

flutter:
  uses-material-design: true
